[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

# Use Ubuntu 22.04 LTS (Jammy) instead of deprecated Ubuntu 20.04 (Focal)
[context.production.environment]
  NETLIFY_BUILD_IMAGE = "jammy"