[build]
  command = "npm run build"
  publish = ".next"
  
[build.environment]
  NODE_VERSION = "18"
  
# Remove Lighthouse plugin temporarily due to Node.js compatibility issues
# [[plugins]]
#   package = "@netlify/plugin-lighthouse"